#ifndef RESOURCE_H
	#define RESOURCE_H

	#ifndef IDC_STATIC
		#define IDC_STATIC	-1
	#endif

	#define	IDD_PLUGINGOLINE_DEMO		2500
	#define	ID_GOLINE_EDIT	(IDD_PLUGINGOLINE_DEMO + 1)
	#define	ID_UGO_STATIC  (IDD_PLUGINGOLINE_DEMO + 5)
#endif

